### PR TITLE
Stripped

### PR DESCRIPTION
**Pull request by micahtk**
Breaks out dependencies of @carnesen/<package>

### CODE REVIEW

**Comment by carnesen** [comment]
Curious why copy-paste those particular dependencies, which are both well-tested and documented in their home repos? Of course you're welcome do so as long as the MIT license of the original software is copied along with the source code.

**Comment by micahtk** [comment]
I'll add the license to the pr once we circle back around. On my end it's the postinstall security vulnerability of NPM, was breaking this out just in case these were left sitting. And also just to say nice CLI framework.

**Comment by carnesen** [comment]
Neither `@carnesen/coded-error` nor `@carnesen/run-and-catch` have any non-dev dependencies so they shouldn't be able to cause any security vulnerabilities from transitive dependencies. (Nor should they have any security vulnerabilities themselves!)

https://github.com/carnesen/run-and-catch/blob/c18aa7545dc6f1625309cea4e6d26fc2675ed5d9/package.json#L21

https://github.com/carnesen/coded-error/blob/15da7a3248a9009d3e8836f13e1e4f751115f1e4/package.json#L24

To your point though, I do intend on maintaining those packages. To that end I just pushed patch releases that simply update the devDependencies. If there's any feature request or problem you encounter with them please feel free to drop a note on their repos.

**Comment by micahtk** [comment]
Maintainer is active

**Pull request closed without merging**
